In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

C:\Users\Piyush\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [6]:
data= pd.read_csv('E:\T v\join data.csv')

In [7]:
data1= pd.DataFrame(data)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 23 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   Instant availability                                                      85 non-null     int64
 1   In hand feel (you can see and compare the product in front of your eyes)  85 non-null     int64
 2   Easy to return                                                            85 non-null     int64
 3   No chance of fraud                                                        85 non-null     int64
 4   Sense of enjoyment                                                        85 non-null     int64
 5   Flexible Payment Method                                                   85 non-null     int64
 6   Explore New Shop                                                          85 non-nul

In [9]:
x=data1[['Product review available','Due to covid 19 you do online shopping','Free Delivery','EMI option available','Notification of sale','Discount'
,'Easy to buy/one click buy','Offers a Range of products','Time Saving',' What is your Family Size','What is your level of Education','What is your Age Group','Gender']]
y=data1[['If you buy from Ecommerce website how frequently you buy']]

In [10]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.15,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [12]:
#instantiate the model
log_regression = LogisticRegression()

#fit the model using the training data
model=log_regression.fit(X_train,y_train)

#use model to make predictions on test data
y_pred = log_regression.predict(X_test)

C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
y_pred

array([1, 3, 1, 0, 3, 1, 3, 1, 1, 0, 1, 1, 1], dtype=int64)

In [14]:
model.coef_

array([[ 8.17149879e-02,  2.04358762e-01, -3.30131409e-01,
         1.03196518e-01,  3.34777642e-02,  3.55782141e-01,
         2.22679023e-01, -1.94363162e-01,  3.57009606e-01,
        -4.72650103e-01, -8.72400117e-02,  1.40889293e-01,
        -2.48683616e-01],
       [-2.08170375e-01,  3.80876226e-01,  6.53739458e-04,
         8.50969310e-02,  2.12709451e-01, -5.15211665e-01,
        -9.36860362e-02,  3.83853378e-01, -9.50466619e-02,
        -6.34445120e-01, -1.57927836e-01,  7.16566307e-02,
        -9.88460477e-02],
       [ 2.06676354e-01, -2.75840744e-01,  1.87126248e-02,
        -4.05539443e-01, -5.78514625e-01,  3.28006503e-01,
        -2.20810389e-01,  3.05700800e-02, -1.00401401e-01,
         7.16131973e-01,  4.50103738e-01, -4.28525142e-01,
         3.53911578e-01],
       [-8.02209677e-02, -3.09394244e-01,  3.10765044e-01,
         2.17245994e-01,  3.32327409e-01, -1.68576979e-01,
         9.18174021e-02, -2.20060297e-01, -1.61561543e-01,
         3.90963249e-01, -2.04935890e

In [15]:
cnf_matrix = pd.DataFrame(metrics.confusion_matrix(y_test, y_pred),index=["Actual: 0","Actual:1","Actual:2","Actual:3"],columns=["predicted:0","predicted:1","predicted:2","predicted:3"])
cnf_matrix

predicted:0  predicted:1  predicted:2  predicted:3
Actual: 0            1            1            0            0
Actual:1             1            7            0            0
Actual:2             0            0            0            2
Actual:3             0            0            0            1

In [16]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6923076923076923


In [17]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score 

In [18]:
print("Mean Absolute Error:", mean_absolute_error(y_test,y_pred))

Mean Absolute Error: 0.3076923076923077


In [19]:
print("Mean Squared Error:",mean_squared_error(y_test,y_pred))

Mean Squared Error: 0.3076923076923077


In [20]:
import statsmodels.api as sd

In [21]:
sd_model = sd.OLS(y,x).fit()
sd_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                                    OLS Regression Results                                                   
=============================================================================================================================
Dep. Variable:     If you buy from Ecommerce website how frequently you buy   R-squared (uncentered):                   0.660
Model:                                                                  OLS   Adj. R-squared (uncentered):              0.598
Method:                                                       Least Squares   F-statistic:                              10.73
Date:                                                      Tue, 19 Jul 2022   Prob (F-statistic):                    3.13e-12
Time:                                                              21:41:56   Log-Likelihood:                         -112.22
No. Observations:                                                        85   AIC:                                      250.4
Df Residuals:                                                            72   BIC:                                      282.2
Df Model:                                                                13                                                  
Covariance Type:                                                  nonrobust                                                  
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Product review available                  -0.0679      0.228     -0.297      0.767      -0.523       0.388
Due to covid 19 you do online shopping    -0.1980      0.132     -1.499      0.138      -0.461       0.065
Free Delivery                              0.3172      0.182      1.748      0.085      -0.045       0.679
EMI option available                       0.0429      0.125      0.342      0.733      -0.207       0.293
Notification of sale                      -0.0669      0.138     -0.485      0.629      -0.342       0.208
Discount                                   0.0143      0.170      0.084      0.933      -0.324       0.353
Easy to buy/one click buy                  0.0055      0.185      0.030      0.976      -0.362       0.373
Offers a Range of products                -0.0708      0.176     -0.402      0.689      -0.422       0.281
Time Saving                               -0.1067      0.171     -0.625      0.534      -0.447       0.234
 What is your Family Size                  0.2328      0.055      4.263      0.000       0.124       0.342
What is your level of Education            0.0433      0.188      0.230      0.819      -0.332       0.419
What is your Age Group                     0.0409      0.230      0.178      0.859      -0.418       0.499
Gender                                     0.3455      0.258      1.339      0.185      -0.169       0.860
==============================================================================
Omnibus:                        4.462   Durbin-Watson:                   2.176
Prob(Omnibus):                  0.107   Jarque-Bera (JB):                4.434
Skew:                           0.550   Prob(JB):                        0.109
Kurtosis:                       2.793   Cond. No.                         24.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [22]:
print("R2 score:",r2_score(y_test,y_pred))

R2 score: 0.4800000000000001


# KNN

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
knn= KNeighborsClassifier(n_neighbors=5 , metric= 'minkowski', p=2)

In [25]:
knn.fit(X_train,y_train)

C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [26]:
y_predK = knn.predict(X_test)
y_predK

array([1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix
cm = pd.DataFrame(confusion_matrix(y_test, y_predK),index=["Actual: 0","Actual:1","Actual:2","Actual:3"],columns=["predicted:0","predicted:1","predicted:2","predicted:3"])
cm

predicted:0  predicted:1  predicted:2  predicted:3
Actual: 0            0            2            0            0
Actual:1             1            6            1            0
Actual:2             0            1            1            0
Actual:3             1            0            0            0

In [28]:
from sklearn.metrics import accuracy_score
ac= accuracy_score(y_test, y_predK)
ac

0.5384615384615384

In [29]:
print("Mean Absolute Error:", mean_absolute_error(y_test,y_predK))

Mean Absolute Error: 0.6153846153846154


In [30]:
print("Mean Squared Error:",mean_squared_error(y_test,y_predK))

Mean Squared Error: 1.0769230769230769


In [31]:
print(metrics.classification_report(y_test,y_predK))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.67      0.75      0.71         8
           2       0.50      0.50      0.50         2
           3       0.00      0.00      0.00         1

    accuracy                           0.54        13
   macro avg       0.29      0.31      0.30        13
weighted avg       0.49      0.54      0.51        13



C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV

In [33]:
#List Hyperparameters that we want to tune.
leaf_size = list(range(1,7))
n_neighbors = list(range(1,14))
p=[1,2]
#Convert to dictionary
hyperparameters = dict(leaf_size=leaf_size, n_neighbors=n_neighbors, p=p)
#Create new KNN object
knn_2 = KNeighborsClassifier()
#Use GridSearch
clf = GridSearchCV(knn_2, hyperparameters, cv=10)
#Fit the model
best_model = clf.fit(x,y)
#Print The value of best Hyperparameters
print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
print('Best p:', best_model.best_estimator_.get_params()['p'])
print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])

C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n

Best leaf_size: 1
Best p: 1
Best n_neighbors: 8


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n

In [34]:
knnHP= clf.fit(X_train,y_train)

C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  UserWarning,
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users

In [35]:
y_predHP = knnHP.predict(X_test)
y_predHP

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1], dtype=int64)

In [36]:
acHP= accuracy_score(y_test, y_predHP)
acHP

0.6153846153846154

In [37]:
cm= pd.DataFrame(confusion_matrix(y_test,y_predHP),index=["Actual: 0","Actual:1","Actual:2","Actual:3"],columns=["predicted:0","predicted:1","predicted:2","predicted:3"])
cm

predicted:0  predicted:1  predicted:2  predicted:3
Actual: 0            1            1            0            0
Actual:1             1            7            0            0
Actual:2             0            2            0            0
Actual:3             0            1            0            0

In [38]:
print(metrics.classification_report(y_test,y_predHP))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.64      0.88      0.74         8
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         1

    accuracy                           0.62        13
   macro avg       0.28      0.34      0.31        13
weighted avg       0.47      0.62      0.53        13



C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Naive Bayes

In [39]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)

C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [40]:
# making a prediction
y_predN = gnb.predict(X_test)
y_predN

array([2, 3, 1, 0, 2, 1, 2, 1, 0, 1, 1, 0, 2], dtype=int64)

In [41]:
 #confusion metric
from sklearn.metrics import confusion_matrix
cm = pd.DataFrame(confusion_matrix(y_test, y_predN),index=["Actual: 0","Actual:1","Actual:2","Actual:3"],columns=["predicted:0","predicted:1","predicted:2","predicted:3"])
cm

predicted:0  predicted:1  predicted:2  predicted:3
Actual: 0            1            1            0            0
Actual:1             2            4            2            0
Actual:2             0            0            2            0
Actual:3             0            0            0            1

In [42]:
# accuracy score
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_predN)
ac

0.6153846153846154

In [45]:
print("Mean Absolute Error:", mean_absolute_error(y_test,y_predN))

Mean Absolute Error: 0.38461538461538464


In [46]:
print("Mean Squared Error:",mean_squared_error(y_test,y_predN))

Mean Squared Error: 0.38461538461538464


In [47]:
print(metrics.classification_report(y_test,y_predN))

              precision    recall  f1-score   support

           0       0.33      0.50      0.40         2
           1       0.80      0.50      0.62         8
           2       0.50      1.00      0.67         2
           3       1.00      1.00      1.00         1

    accuracy                           0.62        13
   macro avg       0.66      0.75      0.67        13
weighted avg       0.70      0.62      0.62        13



In [48]:
param_grid_nb = {'var_smoothing': np.logspace(0,-9, num=100)}

In [49]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
HyperparameterTuning = GridSearchCV(estimator=GaussianNB(), param_grid=param_grid_nb, verbose=1, cv=10, n_jobs=-1)
HyperparameterTuning.fit(X_train, y_train)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  UserWarning,
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(cv=10, estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.848035...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             verbose=1)

In [50]:
print(HyperparameterTuning.best_estimator_)

GaussianNB(var_smoothing=0.12328467394420659)


In [51]:
y_predHPnb = HyperparameterTuning.predict(X_test)
y_predHPnb

array([2, 3, 1, 0, 2, 1, 2, 1, 0, 1, 1, 0, 2], dtype=int64)

In [52]:
acHP = accuracy_score(y_test, y_predHPnb)
acHP

0.6153846153846154

In [53]:
cmatHP = pd.DataFrame(metrics.confusion_matrix(y_test,y_predHPnb),index=["Actual:0","Actual:1","Actual:2","Actual:3"],columns=("Predicted:0","Predicted:1","Predicted:2","Predicted:3"))
cmatHP

Predicted:0  Predicted:1  Predicted:2  Predicted:3
Actual:0            1            1            0            0
Actual:1            2            4            2            0
Actual:2            0            0            2            0
Actual:3            0            0            0            1

In [55]:
print(metrics.classification_report(y_test,y_predHPnb))

              precision    recall  f1-score   support

           0       0.33      0.50      0.40         2
           1       0.80      0.50      0.62         8
           2       0.50      1.00      0.67         2
           3       1.00      1.00      1.00         1

    accuracy                           0.62        13
   macro avg       0.66      0.75      0.67        13
weighted avg       0.70      0.62      0.62        13



# SVM

In [56]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [57]:
x=data1[['Product review available','Due to covid 19 you do online shopping','Free Delivery','EMI option available','Notification of sale','Discount'
,'Easy to buy/one click buy','Offers a Range of products','Time Saving',' What is your Family Size','What is your level of Education','What is your Age Group','Gender']]
y=data1[['If you buy from Ecommerce website how frequently you buy']]

In [58]:
from sklearn.svm import SVC

In [59]:
classifier = SVC(kernel = 'linear', random_state=0)

In [60]:
classifier.fit(X_train,y_train)

C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', random_state=0)

In [61]:
y_preds = classifier.predict(X_test)
y_preds

array([1, 1, 1, 1, 1, 0, 3, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1], dtype=int64)

In [62]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_preds)
cm

array([[1, 4, 0, 0],
       [2, 6, 0, 0],
       [0, 1, 0, 1],
       [1, 1, 0, 0]], dtype=int64)

In [63]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_preds)
ac

0.4117647058823529

In [64]:
print("Mean Absolute Error:", mean_absolute_error(y_test,y_preds))

Mean Absolute Error: 0.7647058823529411


In [65]:
print("Mean Squared Error:",mean_squared_error(y_test,y_preds))

Mean Squared Error: 1.2352941176470589


In [66]:
print(metrics.classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.25      0.20      0.22         5
           1       0.50      0.75      0.60         8
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         2

    accuracy                           0.41        17
   macro avg       0.19      0.24      0.21        17
weighted avg       0.31      0.41      0.35        17



C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# SVM optimiser

In [67]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier()

In [68]:
Parameter_Trials={'n_estimators':[10,20,30,50,70,100],'criterion':['gini','entropy'],'max_depth': [2]}

In [69]:
Random_Search = RandomizedSearchCV(RF, Parameter_Trials, n_iter=5, cv=5, n_jobs=1, verbose=5)

In [70]:
RandomSearchResults=Random_Search.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV 1/5] END criterion=entropy, max_depth=2, n_estimators=70;, score=0.429 total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=2, n_estimators=70;, score=0.429 total time=   0.1s

C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)



[CV 3/5] END criterion=entropy, max_depth=2, n_estimators=70;, score=0.357 total time=   0.1s


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV 4/5] END criterion=entropy, max_depth=2, n_estimators=70;, score=0.462 total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=2, n_estimators=70;, score=0.385 total time=   0.1s

C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)



[CV 1/5] END criterion=gini, max_depth=2, n_estimators=50;, score=0.500 total time=   0.1s


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV 2/5] END criterion=gini, max_depth=2, n_estimators=50;, score=0.429 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=2, n_estimators=50;, score=0.357 total time=   0.1s


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV 4/5] END criterion=gini, max_depth=2, n_estimators=50;, score=0.462 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=2, n_estimators=50;, score=0.385 total time=   0.1s


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV 1/5] END criterion=entropy, max_depth=2, n_estimators=20;, score=0.500 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=2, n_estimators=20;, score=0.357 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=2, n_estimators=20;, score=0.429 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=2, n_estimators=20;, score=0.462 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=2, n_estimators=20;, score=0.385 total time=   0.0s


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV 1/5] END criterion=entropy, max_depth=2, n_estimators=100;, score=0.500 total time=   0.2s


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV 2/5] END criterion=entropy, max_depth=2, n_estimators=100;, score=0.429 total time=   0.2s


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV 3/5] END criterion=entropy, max_depth=2, n_estimators=100;, score=0.429 total time=   0.2s


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV 4/5] END criterion=entropy, max_depth=2, n_estimators=100;, score=0.462 total time=   0.2s


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[CV 5/5] END criterion=entropy, max_depth=2, n_estimators=100;, score=0.385 total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=2, n_estimators=10;, score=0.429 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=2, n_estimators=10;, score=0.429 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=2, n_estimators=10;, score=0.286 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=2, n_estimators=10;, score=0.462 total time=   0.0s


C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector 

[CV 5/5] END criterion=entropy, max_depth=2, n_estimators=10;, score=0.385 total time=   0.0s


In [71]:
RandomSearchResults.best_params_

{'n_estimators': 100, 'max_depth': 2, 'criterion': 'entropy'}

In [72]:
RandomSearchResults.cv_results_['params']

[{'n_estimators': 70, 'max_depth': 2, 'criterion': 'entropy'},
 {'n_estimators': 50, 'max_depth': 2, 'criterion': 'gini'},
 {'n_estimators': 20, 'max_depth': 2, 'criterion': 'entropy'},
 {'n_estimators': 100, 'max_depth': 2, 'criterion': 'entropy'},
 {'n_estimators': 10, 'max_depth': 2, 'criterion': 'entropy'}]

In [73]:
y_predHP = RandomSearchResults.predict(X_test)
y_predHP

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [74]:
cmatdt = pd.DataFrame(metrics.confusion_matrix(y_test,y_predHP),index=["Actual: 0","Actual:1","Actual:2","Actual:3"],columns=["predicted:0","predicted:1","predicted:2","predicted:3"])
cmatdt

predicted:0  predicted:1  predicted:2  predicted:3
Actual: 0            0            5            0            0
Actual:1             0            8            0            0
Actual:2             0            2            0            0
Actual:3             0            2            0            0

In [75]:
ac = accuracy_score(y_test,y_predHP)
ac

0.47058823529411764

In [76]:
print(metrics.classification_report(y_test,y_predHP))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.47      1.00      0.64         8
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         2

    accuracy                           0.47        17
   macro avg       0.12      0.25      0.16        17
weighted avg       0.22      0.47      0.30        17



C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Piyush\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
